#!/bin/sh
# Better Deepin: fetch the Rust crate sources referenced by
# subprojects/*-rs.wrap into subprojects/packagecache, vendor the
# bindgen-cli build tool and its full dependency tree into bindgen/, then
# pack them into the extra upstream tarballs
# ../mesa_<upstream>.orig-subprojects.tar.xz and
# ../mesa_<upstream>.orig-bindgen.tar.xz.
#
# Run this in the top-level source directory on a machine with network
# access and cargo installed, after any upstream version bump (or after
# bumping BINDGEN_VERSION below). Builds themselves never touch the
# network (--wrap-mode=nodownload for meson, and cargo --offline when
# debian/rules compiles the vendored bindgen-cli before meson setup):
# when building from this git checkout the directories are already in the
# working tree; for dsc-based builders (OBS, pbuilder/cowbuilder) the
# tarballs must be shipped with the source package, i.e. committed to the
# OBS package (or uploaded to the fork's releases page and fetched from
# there) together with a .dsc generated by "dpkg-buildpackage -S", so
# that "dpkg-source -x" unpacks them into the build tree.
# debian/rules. The packagecache and bindgen working directories are
# git-ignored, but the produced tarballs are ALSO committed to
# debian/vendor/ (see below) so that a plain git clone can build; keep
# copies next to the regular .orig tarballs too for dsc-based flows.
#
# The crate tarballs are verified against source_hash from each wrap, and
# the bindgen-cli .crate against BINDGEN_SHA256 below.
set -eu

# bindgen-cli is a build tool (meson runs `find_program('bindgen')`), not
# a library crate, so it is not covered by any *-rs.wrap. deepin v25 ships
# a bindgen older than the 0.71.1 minimum required by meson.build (0.72.0
# is blacklisted there), hence we vendor its source and rebuild it offline
# during the package build. Keep in sync with the checks in meson.build.
BINDGEN_VERSION=${BINDGEN_VERSION:-0.73.2}
BINDGEN_SHA256=5622e043625b6d1f32c84f53699690a44d1419e657879de26eb252699f5ebb7c

[ -f debian/changelog ] && [ -d subprojects ] || {
	echo "error: run from the top level of the mesa source tree" >&2
	exit 1
}

SOURCE=$(dpkg-parsechangelog -S Source)
VERSION=$(dpkg-parsechangelog -S Version)
UPSTREAM=${VERSION%-*}
TARBALL="../${SOURCE}_${UPSTREAM}.orig-subprojects.tar.xz"
BINDGEN_TARBALL="../${SOURCE}_${UPSTREAM}.orig-bindgen.tar.xz"

mkdir -p subprojects/packagecache

for w in subprojects/*-rs.wrap; do
	url=$(sed -n 's/^source_url = //p' "$w")
	file=$(sed -n 's/^source_filename = //p' "$w")
	hash=$(sed -n 's/^source_hash = //p' "$w")
	[ -n "$url" ] && [ -n "$file" ] && [ -n "$hash" ] || {
		echo "error: $w lacks source_url/source_filename/source_hash" >&2
		exit 1
	}
	dest="subprojects/packagecache/$file"
	if [ ! -f "$dest" ] || ! echo "$hash  $dest" | sha256sum -c --status -; then
		echo "downloading $file"
		curl -fL --retry 3 -o "$dest" "$url"
		echo "$hash  $dest" | sha256sum -c -
	else
		echo "cached    $file"
	fi
done

# Vendor bindgen-cli: download the published crate, extract it and pin its
# complete dependency tree into bindgen/bindgen-cli-<version>/vendor via
# "cargo vendor --locked", so debian/rules can later build it with
# "cargo build --release --offline --locked".
command -v cargo >/dev/null || {
	echo "error: cargo is required to vendor bindgen-cli" >&2
	exit 1
}
crate="bindgen-cli-${BINDGEN_VERSION}.crate"
rm -rf bindgen
mkdir -p bindgen
echo "downloading $crate"
curl -fL --retry 3 -o "bindgen/$crate" \
	"https://static.crates.io/crates/bindgen-cli/$crate"
echo "$BINDGEN_SHA256  bindgen/$crate" | sha256sum -c -
tar -xf "bindgen/$crate" -C bindgen
rm -f "bindgen/$crate"
(
	cd "bindgen/bindgen-cli-${BINDGEN_VERSION}"
	mkdir -p .cargo
	cargo vendor --locked vendor > .cargo/config.toml
	[ -s .cargo/config.toml ] && [ -d vendor ] || {
		echo "error: cargo vendor produced no output" >&2
		exit 1
	}
)

# dpkg-source unpacks additional .orig-<component> tarballs into a
# top-level directory named after the component (replacing any existing
# one), so each tarball carries its directory's complete contents under a
# "<source>-<upstream>/" prefix. Note this unpacking happens with
# "dpkg-source -x" (dsc-based builds, e.g. OBS); when building directly
# from this git checkout the directories are already in the working tree.
tar -cJf "$TARBALL" \
	--transform "s#^subprojects#${SOURCE}-${UPSTREAM}#" \
	--mode=u+rw subprojects

tar -cJf "$BINDGEN_TARBALL" \
	--transform "s#^bindgen#${SOURCE}-${UPSTREAM}#" \
	--mode=u+rw bindgen

# Commit copies into debian/vendor/: debian/ is tarred verbatim into the
# .debian.tar.xz (no binary-file restrictions) and travels with the git
# repo, so git-clone builders (e.g. OBS building this repo directly, where
# subprojects/packagecache and bindgen/ are git-ignored and thus absent)
# can self-bootstrap: debian/rules unpacks these when the directories are
# missing. dsc-based builders additionally get them via "dpkg-source -x"
# from the ../ copies listed in the .dsc.
mkdir -p debian/vendor
cp -f "$TARBALL" "$BINDGEN_TARBALL" debian/vendor/

# dpkg-source refuses binary files under debian/ unless listed here.
: > debian/source/include-binaries
for t in debian/vendor/mesa_*.orig-*.tar.xz; do
	echo "$t" >> debian/source/include-binaries
done

sha256sum "$TARBALL" "$BINDGEN_TARBALL"
